# This would normally not be pushed to VCS and instead an encrypted SealedSecret manifest would be created and applied by the GitOps tool of choice.
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  labels:
    app: rabbitmq
type: Opaque
data:
  rabbitmq_default_user: Z3Vlc3Q=
  rabbitmq_default_pass: Z3Vlc3Q=
